---
  - hosts: video
    remote_user: user
    tasks:
      - name: Copy videos
        ansible.builtin.copy:
          src: ../../video/
          dest: /home/user/src/More-Heat-Than-Light/video/
          owner: user
          group: user
          mode: '0644'
